image: rocker/r-base:latest

pages:
  stage: deploy
  
  before_script:
    - apt-get update -qq
    - apt-get install -t unstable software-properties-common --yes
    - apt-get install -t unstable --yes libssl-dev libssh2-1-dev libxml2-dev libcurl4-gnutls-dev libgit2-dev libmagick++-dev pandoc pandoc-citeproc

  script:
    - Rscript -e 'install.packages(c("remotes", "pkgdown", "dplyr", "readr", "pillar", "stringr", "testthat"))'
    - Rscript -e 'remotes::install_github("tidyverse/tibble")'
    - Rscript -e 'remotes::install_gitlab("dickoa/rhxl")'
    - Rscript -e 'pkgdown::build_site()'
    - mv docs public
    
  artifacts:
    paths:
      - public
